# Generated by Django 4.2.3 on 2023-08-29 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="kew_skill",
            new_name="key_skill",
        ),
    ]
