# Generated by Django 4.2.3 on 2023-08-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_rename_kew_skill_project_key_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.profile",
            ),
        ),
    ]
