# Generated by Django 4.2.3 on 2023-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="key_skill",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="keyword",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
