# Generated by Django 4.2.3 on 2023-08-29 19:53

from django.db import migrations, models
import django.db.models.deletion
import projects.validators


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0006_alter_project_description_alter_project_github_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CertifyingInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[projects.validators.count_char],
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        validators=[projects.validators.count_char]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[projects.validators.count_char],
                    ),
                ),
                (
                    "timestamp",
                    models.DateField(
                        validators=[projects.validators.count_char]
                    ),
                ),
                (
                    "certifying_institution",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutes",
                        to="projects.certifyinginstitution",
                        validators=[projects.validators.count_char],
                    ),
                ),
                (
                    "profiles",
                    models.ManyToManyField(
                        default=2,
                        related_name="certificates",
                        to="projects.profile",
                        validators=[projects.validators.count_char],
                    ),
                ),
            ],
        ),
    ]
